Define data audit result structure
nspcc-dev/neofs-api pull request #114
Opened 2020-12-17 15:02 UTC by realloc

Inner ring nodes conduct data audit and submit audit results. Results are then saved in audit smart contract for settlement routines to transfer payments.

We don't need to save the full detailed audit report, but only provide enough information for other subsystems to reward or punish storage nodes.

Closes: #109

2020-12-17 15:33 UTC, alexvanin requested changes

2020-12-17 15:33 UTC, alexvanin commented on audit/types.proto
> +  uint64 audit_epoch = 1 [json_name = "auditEpoch"];
To avoid varint issues in contract I propose to use `fixed64` type for epochs.

2020-12-17 15:33 UTC, alexvanin commented on audit/types.proto
> +  // List of storage node public keys that passed at least one PDP
that **failed** at least one PDP

2020-12-17 15:33 UTC, alexvanin commented on audit/types.proto
> +  // policy or not found at all when checking PoP
Maybe we should notice that `hit`, `miss` and `fail` are counters in audit **sample** and it is not precise values? E.g. `Number of objects under audit sample stored ...`

2020-12-17 15:45 UTC, realloc commented on audit/types.proto
> +  // List of storage node public keys that passed at least one PDP
fixed

2020-12-17 16:10 UTC, alexvanin approved these changes

2020-12-17 16:57 UTC, cthulhu-rider submitted a review, later dismissed

2020-12-18 11:26 UTC, alexvanin approved these changes

2020-12-18 11:27 UTC, merged