Support container sessions
nspcc-dev/neofs-api pull request #158
Opened 2021-05-24 11:24 UTC by cthulhu-rider

Closes #156 
Closes #157.

2021-05-24 12:25 UTC, realloc requested changes
LGTM, but requiers minor documentation comments format changes

2021-05-24 12:25 UTC, realloc commented on session/types.proto
> +// Context information for Session Tokens related to ContainerService requests
There should be a dot at the end of the sentence

2021-05-24 12:25 UTC, realloc commented on session/types.proto
> +    // Spreads the action to all owner containers.
Breaks pandoc format. Must be one line.

2021-05-24 12:25 UTC, realloc commented on session/types.proto
> +    //
Breaks pandoc format. Must be one line.

2021-06-03 08:17 UTC, alexvanin approved these changes

2021-06-03 08:36 UTC, realloc approved these changes

2021-06-03 08:36 UTC, merged